HHH-10264 - Values weren't cached after persist
HHH-9140 - Allow to look for id outside of context
ERROR CollectionCacheInvalidator:145 - org.hibernate.TransientObjectException: The instance was not associated with this session
	at org.hibernate.internal.SessionImpl.getIdentifier(SessionImpl.java:1511)
(cherry picked from commit f0d8fcd)

Added property to propagate error in test case

Test case without mappedBy
org.hibernate.HibernateException: Unable to resolve property:
	at org.hibernate.tuple.entity.EntityMetamodel.getPropertyIndex(EntityMetamodel.java:926)

(cherry picked from commit bf2eb018563c09162308981193a26055e4d5e09c)