HHH-19386 MutationSpecificationImpl#getResultType must return null
Returning `Void.class` causes the validation in `QuerySqmImpl`
to fail with the error:
```
org.hibernate.query.IllegalQueryOperationException: Result type given for a non-SELECT Query [<criteria>]
```

when the query is executed like in the example:
```java
MutationSpecification  mutationSpecification  = MutationSpecification.create( ... )
session
   .createQuery(mutationSpecification.reference())
   .executeUpdate();
```