Align JUnit versions for JFR module
to prevent failures as:

Caused by: org.junit.platform.commons.JUnitException: The wrapped NoClassDefFoundError is likely caused by the versions of JUnit jars on the classpath/module path not being properly aligned.
Please ensure consistent versions are used (see https://docs.junit.org/6.0.1/user-guide/#dependency-metadata).
The following conflicting versions were detected:
- org.junit.jupiter.api: 6.0.1
- org.junit.jupiter.engine: 6.0.1
- org.junit.platform.commons: 6.0.1
- org.junit.platform.engine: 6.0.1
- org.junit.platform.launcher: 6.0.1
- org.junit.vintage.engine: 5.8.2